# Generated by Django 5.0 on 2023-12-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiencenceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='None', max_length=100, unique=True)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
