# Generated by Django 5.0 on 2023-12-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsense', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiencenceUser',
        ),
    ]
