# Generated by Django 5.0 on 2023-12-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adsense', '0002_delete_liencenceuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiencenceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('host', models.CharField(default='None', max_length=100, unique=True)),
                ('valid_end_date', models.DateTimeField()),
            ],
        ),
    ]
