# Generated by Django 5.0 on 2023-12-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsense', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liencenceuser',
            name='host',
            field=models.CharField(blank=True, default='None', max_length=100, null=True, unique=True),
        ),
    ]
