# Generated by Django 5.0 on 2023-12-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsense', '0004_alter_liencenceuser_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liencenceuser',
            name='host',
            field=models.CharField(default='None', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='liencenceuser',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
