# Generated by Django 5.0 on 2023-12-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsense', '0005_alter_liencenceuser_host_alter_liencenceuser_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liencenceuser',
            name='host',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
