# Generated by Django 5.0 on 2024-02-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsense', '0006_alter_liencenceuser_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(max_length=255, unique=True)),
                ('user', models.ManyToManyField(to='adsense.liencenceuser')),
            ],
        ),
    ]
